# Generated by Django 4.0.10 on 2023-03-28 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
