# Generated by Django 4.0.10 on 2023-06-20 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locker',
        ),
    ]
