# Generated by Django 4.0.10 on 2023-06-23 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_locker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TimeOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Locker',
        ),
        migrations.DeleteModel(
            name='UnlockTime',
        ),
        migrations.AddField(
            model_name='passwordoperator',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.timeoperator'),
        ),
    ]
