# Generated by Django 4.0.10 on 2023-06-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_passwordoperator_timeoperator_delete_locker_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordOperator',
        ),
        migrations.DeleteModel(
            name='TimeOperator',
        ),
    ]
