# Generated by Django 4.0.10 on 2023-06-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0007_delete_passwordoperator_delete_timeoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.timeoperator')),
            ],
        ),
    ]
