# Generated by Django 4.0.10 on 2023-06-23 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordOperator',
        ),
        migrations.DeleteModel(
            name='TimeOperator',
        ),
    ]
