# Generated by Django 4.0.10 on 2023-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0009_delete_passwordoperator_delete_timeoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
