# Generated by Django 4.0.10 on 2023-06-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordOperator',
        ),
    ]
