# Generated by Django 4.0.10 on 2023-06-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_delete_passwordoperator'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
                ('label', models.CharField(max_length=20)),
            ],
        ),
    ]
